// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8BRr3gV1e7gfk-AuOC-xk5-IP27BLfTU',
    appId: '1:661289170436:web:9fd68e360d53184186e751',
    messagingSenderId: '661289170436',
    projectId: 'coffeshop-c9787',
    authDomain: 'coffeshop-c9787.firebaseapp.com',
    storageBucket: 'coffeshop-c9787.appspot.com',
    measurementId: 'G-M4TEMD9MY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc2mKRdI2S8zpqqY77TUq-VVkid7EbkWc',
    appId: '1:661289170436:android:1527575b2c66310e86e751',
    messagingSenderId: '661289170436',
    projectId: 'coffeshop-c9787',
    storageBucket: 'coffeshop-c9787.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoh0Eh_wQqswCJZcE4b9pPDqK2CwaqICw',
    appId: '1:661289170436:ios:ac721df6602ce3e486e751',
    messagingSenderId: '661289170436',
    projectId: 'coffeshop-c9787',
    storageBucket: 'coffeshop-c9787.appspot.com',
    iosBundleId: 'com.example.coffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoh0Eh_wQqswCJZcE4b9pPDqK2CwaqICw',
    appId: '1:661289170436:ios:ac721df6602ce3e486e751',
    messagingSenderId: '661289170436',
    projectId: 'coffeshop-c9787',
    storageBucket: 'coffeshop-c9787.appspot.com',
    iosBundleId: 'com.example.coffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8BRr3gV1e7gfk-AuOC-xk5-IP27BLfTU',
    appId: '1:661289170436:web:b364661623f96ed486e751',
    messagingSenderId: '661289170436',
    projectId: 'coffeshop-c9787',
    authDomain: 'coffeshop-c9787.firebaseapp.com',
    storageBucket: 'coffeshop-c9787.appspot.com',
    measurementId: 'G-RG80BLTT2N',
  );
}
